[RDPP 4451] Fix inner join and partially switch on the test suite
appcelerator/appc.composite pull request #15
Opened 2018-04-23 09:10 UTC by pltod2

2018-04-23 21:23 UTC, todanator requested changes

2018-04-23 21:23 UTC, todanator commented on test/batched.js
> -	it('should be able to batched find all', function (next) {
You can put a "skip" on the "describe" instead of all of these

2018-04-23 21:23 UTC, todanator commented on test/common.js
> +// NOTE: SKIPPED UNTIL EXTERNAL SERVICES ARE RESOLVED
This is until we can sort out how to do integration tests better right? If so I would suggest putting a link to our JIRA ticket

2018-04-23 21:23 UTC, todanator commented on test/inner_join.js
> +	// before(function (done) {
Same, you can probably do a 'skip' on the 'describe'

2018-04-23 21:23 UTC, todanator commented on test/joins_one_to_many_test.js
> +describe('Composite - One to Many', function () {
It seems like the left join tests should go in left_join.js and the inner join tests should go in inner_join.js

2018-04-23 21:23 UTC, todanator commented on test/inner_join.js
> +	it.skip('API-285: should support inner join', function (next) {
Couldn't these tests be updated to work? They depend on memory connector just like Author/Post.

2018-04-23 21:23 UTC, todanator commented on test/joins_one_to_many_test.js
> +	it('[RDPP-4451] Left Join Array - No Alias - With Multiple', function (next) {
These don't appear to be generated testids.

2018-04-23 21:23 UTC, todanator commented on test/left_join.js
> +	it.skip('should warn when joined on a bad model', function (next) {
Here too, seems like these should be updated to use the arrow server in your utils.js.

2018-04-24 08:26 UTC, pltod2 commented on test/joins_one_to_many_test.js
> +describe('Composite - One to Many', function () {
You are right but I will approach it differently. I will just delete the old one to remove confusion. All the cases are covered by the new classification one to many and one to one. I believe such classification is much more useful than inner - left join.

2018-04-24 08:28 UTC, pltod2 commented on test/joins_one_to_many_test.js
> +	it('[RDPP-4451] Left Join Array - No Alias - With Multiple', function (next) {
Yes. They are manual we do not have script for this project that supports automatic generation

2018-04-24 11:21 UTC, pltod2 commented on test/batched.js
> -	it('should be able to batched find all', function (next) {
No skips anymore. Old code is in separate suite that is not considered.

2018-04-24 11:21 UTC, pltod2 commented on test/common.js
> +// NOTE: SKIPPED UNTIL EXTERNAL SERVICES ARE RESOLVED
Comment added in dedicated readme

2018-04-24 11:22 UTC, pltod2 commented on test/inner_join.js
> +	it.skip('API-285: should support inner join', function (next) {
These are not going to be needed anymore unless they are integration tests

2018-04-24 11:22 UTC, pltod2 commented on test/left_join.js
> +	it.skip('should warn when joined on a bad model', function (next) {
These are not going to be needed anymore unless they are integration tests

2018-04-24 21:27 UTC, merged