[ARRCONN-51] Fixed issue when makes a query with nonexistent id
appcelerator/appc.composite pull request #4
Opened 2017-01-11 15:12 UTC by vladimir-trifonov

https://jira.appcelerator.org/browse/ARRCONN-51

2017-01-17 03:06 UTC, janvennemann requested changes

2017-01-17 03:06 UTC, janvennemann commented on lib/utility/runJoin.js
> +			if (instance0) {
You don't need to wrap this in an extra if-else block if you just add `if (isCollection && instance0)` in L21. That will have the same effect.

2017-01-17 11:24 UTC, vladimir-trifonov commented on lib/utility/runJoin.js
> +			if (instance0) {
Done!

2017-01-19 16:04 UTC, janvennemann approved these changes

2017-01-19 16:04 UTC, merged